---
- hosts: agents
  remote_user: root
  tasks:
  - name: install basic packages
    yum:  name=hwloc,hwloc-libs,numactl,numactl-libs

  - name: install mesos repository
    yum:  name=http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-2.noarch.rpm state=present

  - name: install mesos
    yum:  name=mesos,mesosphere-el-repo

  - name: install mesos-slave isolation file
    copy: src=isolation
          dest=/etc/mesos-slave/isolation

  - name: extract JDK8
    unarchive: src=jdk-8u102-linux-x64.tar.gz
               dest=/usr/java/

  - name: link to latest JDK8; this may break existing JDK installation
    command: "{{ item }}"
    with_items:
        - rm -f /usr/java/latest
        - ln -sF /usr/java/jdk1.8.0_102 /usr/java/latest

  - name: install mesos-slave cgroups file
    copy: src=cgroups_enable_cfs
          dest=/etc/mesos-slave/cgroups_enable_cfs

  - name: Start Mesos Agent
    service: name=mesos-slave state=restarted

- hosts: masters
  remote_user: root
  tasks:
  - name: install basic packages
    yum:  name=hwloc,hwloc-libs,numactl,numactl-libs

  - name: install mesos repository
    yum:  name=http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-2.noarch.rpm state=present

  - name: install mesos,marathon
    yum:  name=mesos,mesosphere-el-repo,marathon

  - name: extract JDK8
    unarchive: src=jdk-8u102-linux-x64.tar.gz
               dest=/usr/java/

  - name: link to latest JDK8; this may break existing JDK installation
    command: "{{ item }}"
    with_items:
        - rm -f /usr/java/latest
        - ln -sF /usr/java/jdk1.8.0_102 /usr/java/latest

  - name: install zookeeper location file
    copy: src=zk
          dest=/etc/mesos/zk

  - name: start mesos master
    service: name=mesos-master state=restarted

  - name: start marathon
    service: name=marathon state=restarted

- hosts: retz-server
  remote_user: root
  tasks:
  - name: install retz server
    yum: name=https://github.com/retz/retz/releases/download/0.0.23/retz-server-0.0.23-1.el7.x86_64.rpm state=present

  - name: install retz config file
    template: src=retz.properties.j2
              dest=/opt/retz-server/etc/retz.properties

- hosts: retz-client
  remote_user: root
  tasks:
  - name: install retz server
    yum: name=https://github.com/retz/retz/releases/download/0.0.23/retz-client-0.0.23-1.el7.x86_64.rpm state=present

  - name: install retz config file
    template: src=retz.properties.j2
              dest=/opt/retz-client/etc/retz.properties
